### ISSUE TITLE
waitForText not working in case of newLine character

### ISSUE THREAD

**Issue by Drusy** [openium/SwiftiumTestingKit#1]
The following code should work

```swift
// ViewController
label.text = "Some \n text"

// Test
let found = solo.waitFor(text: "Some \n text")
XCTAssertTrue(found) // Fail
```

**Comment by kenji21** [comment]
Added a test:

```
(lldb) po viewController.topLabel.accessibilityLabel
▿ Optional<String>
  - some : "Some   text"
```

Seems \n is eaten by accessibility, fixed in https://github.com/openium/SwiftiumTestingKit/releases/tag/v0.1.6

**Comment by Drusy** [comment]
The problem resurfaced with a double \n\n

**Comment by Drusy** [comment]
Should be fixed in https://github.com/openium/SwiftiumTestingKit/releases/tag/v0.6.1
