### ISSUE TITLE
waitFor(text:) does not work with UITextView

### ISSUE THREAD

**Issue by Drusy** [openium/SwiftiumTestingKit#2]

**Comment by kenji21** [comment]
It seems that UITextView has some specifics with accessibility (used to find view using their accessibility labels)

Here is a test code reproducing your issue (added in STKSoloTests.swift in my local clone):

```
    func testWaitForText_inTextView_shouldBeFound() {
        // Given
        let text = "Lorem ipsum textview"
        sut.showViewControllerInCleanWindow(viewController)
        
        // When
        self.viewController.textView.accessibilityLabel = text
        let waitForText = sut.waitFor(text: text)
        sut.window?.printHierarchy()
        //sut.waitForever()
        
        // Expect
        XCTAssertTrue(waitForText)
    }
```

Commmenting out `self.viewController.textView.accessibilityLabel = text` make printHierarchy showing:

```
|    |    |    |    UITextView
```

while with the line, it shows:

```
|    |    |    |    UITextView, label: Lorem ipsum textview
```

I'll commit this test, but just to have it as a "documentation"
